
version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: trebolsoft
    ports: ["5432:5432"]
    volumes:
      - ./db-data:/var/lib/postgresql/data
  api:
    build: ./api
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@db:5432/trebolsoft
      API_V1_STR: /api/v1
      SUPABASE_PROJECT_URL: http://localhost
      SUPABASE_JWKS_URL: http://localhost
      SUPABASE_SERVICE_ROLE_KEY: dev-only
      CORS_ORIGINS: http://localhost:8081
    ports: ["8000:8000"]
    depends_on: [db]
